"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
var core_1 = require("@angular/core");
var FooterComponent = (function () {
    function FooterComponent() {
    }
    return FooterComponent;
}());
FooterComponent = tslib_1.__decorate([
    core_1.Component({
        selector: 'app-footer',
        template: "\n        <footer class=\"android-footer mdl-mega-footer\">\n            <div class=\"mdl-mega-footer--top-section\">\n                <div class=\"mdl-mega-footer--left-section\">\n                    <button class=\"mdl-mega-footer--social-btn\"></button>\n                    &nbsp;\n                    <button class=\"mdl-mega-footer--social-btn\"></button>\n                    &nbsp;\n                    <button class=\"mdl-mega-footer--social-btn\"></button>\n                </div>\n                <div class=\"mdl-mega-footer--right-section\">\n                    <a class=\"mdl-typography--font-light\" href=\"#top\">\n                        Back to Top\n                        <i class=\"material-icons\">expand_less</i>\n                    </a>\n                </div>\n            </div>\n            <div class=\"mdl-mega-footer--middle-section\">\n                <p class=\"mdl-typography--font-light\">Satellite imagery: \u00A9 2014 Astrium, DigitalGlobe</p>\n                <p class=\"mdl-typography--font-light\">Some features and devices may not be available in all areas</p>\n            </div>\n            <div class=\"mdl-mega-footer--bottom-section\">\n                <a class=\"android-link android-link-menu mdl-typography--font-light\" id=\"version-dropdown\">\n                    Versions\n                    <i class=\"material-icons\">arrow_drop_up</i>\n                </a>\n                <ul class=\"mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect\" for=\"version-dropdown\">\n                    <li class=\"mdl-menu__item\">5.0 Lollipop</li>\n                    <li class=\"mdl-menu__item\">4.4 KitKat</li>\n                    <li class=\"mdl-menu__item\">4.3 Jelly Bean</li>\n                    <li class=\"mdl-menu__item\">Android History</li>\n                </ul>\n                <a class=\"android-link android-link-menu mdl-typography--font-light\" id=\"developers-dropdown\">\n                    For Developers\n                    <i class=\"material-icons\">arrow_drop_up</i>\n                </a>\n                <ul class=\"mdl-menu mdl-js-menu mdl-menu--top-left mdl-js-ripple-effect\" for=\"developers-dropdown\">\n                    <li class=\"mdl-menu__item\">App developer resources</li>\n                    <li class=\"mdl-menu__item\">Android Open Source Project</li>\n                    <li class=\"mdl-menu__item\">Android SDK</li>\n                    <li class=\"mdl-menu__item\">Android for Work</li>\n                </ul>\n                <a class=\"android-link mdl-typography--font-light\" href=\"\">Blog</a>\n                <a class=\"android-link mdl-typography--font-light\" href=\"\">Privacy Policy</a>\n            </div>\n        </footer>\n    ",
    })
], FooterComponent);
exports.FooterComponent = FooterComponent;
//# sourceMappingURL=footer.js.map