"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CARDES = [
    { Id: 1, Name: "Family", Type: 4, url: require("../../../assets/img/card_credit.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "Miễn phí rút tiền mặt tại ATM Sacombank", TIC1: "200.000 VNĐ", TIC2: "Từ 10 triệu đến dưới 200 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "Không miễn lãi", TIC5: "50%-80%", TIC6: "done", TIC7: "", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 1 - Card", detail3: "Thông tin chi tiết 1 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 2, Name: "UPI card", Type: 3, url: require("../../../assets/img/card_credit1.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "", TIC1: "299.000 VNĐ", TIC2: "Từ 10 triệu đến dưới 200 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 2 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 2 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 3, Name: "Visa Ladies Frist", Type: 3, url: require("../../../assets/img/card_credit2.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "", TIC1: "299.000 VNĐ", TIC2: "Từ 10 triệu đến dưới 200 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 3 - Card", detail2: "Thông tin chi tiết 3 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 4, Name: "Visa Classic", Type: 3, url: require("../../../assets/img/card_credit3.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "", TIC1: "299.000 VNĐ", TIC2: "Từ 10 triệu đến dưới 20 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 6, Name: "Master Card Classic", Type: 3, url: require("../../../assets/img/card_credit5.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "", TIC1: "299.000 VNĐ", TIC2: "Từ 10 triệu đến dưới 20 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 7, Name: "JCB Motor Card", Type: 4, url: require("../../../assets/img/card_credit6.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "Miễn phí rút tiền mặt tại ATM Sacombank", TIC1: "299.000 VNĐ", TIC2: "Từ 10 triệu đến dưới 20 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50% - 80%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 8, Name: "Visa Gold", Type: 3, url: require("../../../assets/img/card_credit7.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "", TIC1: "399.000 VNĐ", TIC2: "Từ 20 triệu đến 50 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 9, Name: "Master Card Gold", Type: 3, url: require("../../../assets/img/card_credit8.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "", TIC1: "399.000 VNĐ", TIC2: "Từ 20 triệu đến dưới 200 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 10, Name: "JCB Car Card", Type: 4, url: require("../../../assets/img/card_credit9.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "Miễn phí rút tiền mặt tại ATM Sacombank", TIC1: "399.000 VNĐ", TIC2: "Từ 20 triệu đến dưới 50 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%-80%", TIC6: "done", TIC7: "done", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 11, Name: "Visa Platinum", Type: 3, url: require("../../../assets/img/card_credit1.jpg"), TIVT1: "Bảo hiểm tai nạn du lịch toàn cầu 10,5 tỷ đồng. Bảo hiểm mất hành lý với mức bồi thường 10,5 triệu đồng. Bảo hiểm hành lý trả trậm với mức bồi thường 5,25 triệu đồng. Bảo hiểm trì hoãn chuyến bay với mức bồi thường 5,25 triệu đồng", TIVT2: "Tặng thẻ thành viên và 2 lượt sử dụng khi đạt doanh số chi tiêu 200 triệu/năm tại thời điểm xét doanh số. Tặng thêm 2 lượt sử dụng với mỗi 100 triệu đồng doanh số giao dịch thanh toán hàng quý", TIVT3: "", TIVT4: "", TIC1: "999.000 VNĐ", TIC2: "Từ 50 triệu VNĐ", TIC3: "1,6% - 2,15%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Gold", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 12, Name: "Visa Signature", Type: 1, url: require("../../../assets/img/card_credit2.jpg"), TIVT1: "Bảo hiểm tai nạn du lịch toàn cầu 10,5 tỷ đồng. Bảo hiểm mất hành lý với mức bồi thường 10,5 triệu đồng. Bảo hiểm hành lý trả trậm với mức bồi thường 5,25 triệu đồng. Bảo hiểm trì hoãn chuyến bay với mức bồi thường 5,25 triệu đồng", TIVT2: "Miễn phí sử dụng phòng chờ với mỗi doanh số giao dịch 100 triệu đồng/quý được tặng 2 lượt sử dụng", TIVT3: "", TIVT4: "Tích lũy dặm Sacombank. Tặng 500 dặm cho giao dịch đầu tiên. Tặng thêm 4.500 dặm khi đạt 100 triệu đồng doanh số giao dịch", TIC1: "1.499.000 VNĐ", TIC2: "Từ 200 triệu VNĐ", TIC3: "1,6% - 2,15%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "", class: "Gold", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 13, Name: "MasterCard World", Type: 3, url: require("../../../assets/img/card_credit3.jpg"), TIVT1: "Bảo hiểm tai nạn du lịch toàn cầu 10,5 tỷ đồng. Bảo hiểm mất hành lý với mức bồi thường 10,5 triệu đồng. Bảo hiểm hành lý trả trậm với mức bồi thường 5,25 triệu đồng. Bảo hiểm trì hoãn chuyến bay với mức bồi thường 5,25 triệu đồng", TIVT2: "Miễn phí thường niên, tặng 2 lượt sử dụng đầu tiên. Tặng thêm 2 lượt sử dụng với mỗi 100 triệu đồng doanh số giao dịch thanh toán hàng quý", TIVT3: "Tặng 3 lượt sử dụng/năm", TIVT4: "", TIC1: "1.499.000 VNĐ", TIC2: "Từ 200 triệu VNĐ", TIC3: "1,6% - 2,5%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Gold", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 14, Name: "Visa Infinite", Type: 3, url: require("../../../assets/img/card_credit4.jpg"), TIVT1: "Bảo hiểm tai nạn du lịch toàn cầu 22 tỷ đồng", TIVT2: "Miễn phí thường niên. Không giới hạn lượt sử dụng", TIVT3: "Tặng 12 lượt sử dụng/năm", TIVT4: "Tặng 01 đêm nghỉ dưỡng cao cấp trị giá 23 triệu đồng", TIC1: "19.999.000 VNĐ", TIC2: "Từ 500 triệu VNĐ", TIC3: "2,15%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "done", class: "Gold", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
    { Id: 15, Name: "Visa Platinum Cashback", Type: 2, url: require("../../../assets/img/card2.jpg"), TIVT1: "", TIVT2: "", TIVT3: "", TIVT4: "", TIC1: "999.000 VNĐ", TIC2: "Từ 50 triệu VNĐ", TIC3: "1,6% - 2,15%", TIC4: "55 ngày", TIC5: "50%", TIC6: "done", TIC7: "", class: "Classic", detail1: "Thông tin chi tiết 1 - Card", detail2: "Thông tin chi tiết 2 - Card", detail3: "Thông tin chi tiết 3 - Card", icondetail1: "card_giftcard", icondetail2: "card_giftcard", icondetail3: "card_giftcard" },
];
exports.CONTENT = [
    { ContentType: 1, title: "Dặm bay", contentline1: "Tận hưởng cuộc sống thú vị và ngập tràn ưu đãi với thẻ tín dụng Sacombank - nguồn tài chính dự phòng thiết yếu cho mọi nhu cầu chi tiêu, mua sắm", contentline2: "Sacombank cung cấp nhanh chóng, linh hoạt và kinh tế nhất với các sản phẩm dịch vụ đa dạng.", contentline3: "Hail a taxi, find a recipe, run through a temple – Google Play has all the apps and games that let you make your Android device uniquely yours", contentline4: "Nhận 01 Dặm PremierMile cho mỗi 25.000 VND chi tiêu trong nước và 20.000 VND chi tiêu nước ngoài để quy đổi vé máy bay, đêm nghỉ khách sạn hoặc chi trả chi phí du lịch.", iconline1: "assignment", iconline2: "card_giftcard", iconline3: "card_giftcard", iconline4: "person" },
    {
        ContentType: 2, title: "Hoàn tiền", contentline1: "Ưu đãi khi mở thẻ sacombank PremierMiles trực tuyến thành công: Nhận ngay vali 24 phiên bản đặc biệt.", contentline2: "Nhận 01 Dặm PremierMile cho mỗi 25.000 VND chi tiêu trong nước và 20.000 VND chi tiêu nước ngoài để quy đổi vé máy bay, đêm nghỉ khách sạn hoặc chi trả chi phí du lịch.", contentline3: "Tặng thẻ Priority Pass vào phòng chờ VIP tại hơn 900 sân bay quốc tế kèm 01 lần sử dụng dịch vụ miễn phí mỗi quý.", contentline4: "Quyền lợi chung của thẻ sacombank: Ưu đãi mua sắm trả góp sacombank 0% Mọi Nơi; nâng cỡ ly Starbucks miễn phí; miễn phí 1 bắp + 2 nước ngọt khi mua 2 vé xem phim tại rạp CGV vào mỗi thứ Bảy; hàng ngàn ưu đãi khắp thế giới theo chương trình sacombank World Priviledge và Visa Signature hoặc World Mastercard.", iconline1: "card_giftcard", iconline2: "assignment", iconline3: "card_giftcard", iconline4: "card_giftcard"
    },
    { ContentType: 3, title: "Điểm thưởng", contentline1: "Quyền lợi chung của thẻ sacombank: Ưu đãi mua sắm trả góp sacombank 0% Mọi Nơi; nâng cỡ ly Starbucks miễn phí; miễn phí 1 bắp + 2 nước ngọt khi mua 2 vé xem phim tại rạp CGV vào mỗi thứ Bảy; hàng ngàn ưu đãi khắp thế giới theo chương trình sacombank World Priviledge và Visa Signature hoặc World Mastercard.", contentline2: "content line 2", contentline3: "content line 3", contentline4: "content line 4", iconline1: "card_giftcard", iconline2: "card_giftcard", iconline3: "assignment", iconline4: "card_giftcard" },
    { ContentType: 4, title: "Rút tiền mặt miễn phí", contentline1: "content line 1", contentline2: "Quyền lợi chung của thẻ sacombank: Ưu đãi mua sắm trả góp sacombank 0% Mọi Nơi; nâng cỡ ly Starbucks miễn phí; miễn phí 1 bắp + 2 nước ngọt khi mua 2 vé xem phim tại rạp CGV vào mỗi thứ Bảy; hàng ngàn ưu đãi khắp thế giới theo chương trình sacombank World Priviledge và Visa Signature hoặc World Mastercard.", contentline3: "content line 3", contentline4: "content line 4", iconline1: "card_giftcard", iconline2: "card_giftcard", iconline3: "assignment", iconline4: "person" },
];
//# sourceMappingURL=Card-Data.js.map